services:
    bakasura.xforwardedfor.listener:
        class: bakasura\xforwardedfor\event\listener
        arguments:
            - '@request'
            - '@config_text'
        tags:
            - { name: event.listener }

    bakasura.xforwardedfor.cloudflare_ip_fetcher:
        class: bakasura\xforwardedfor\service\cloudflare_ip_fetcher
        arguments:
            - '@config_text'
            - '@config'
